spring:
  profiles:
    active: local

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/logback
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update